### ISSUE TITLE
Help !!

### ISSUE THREAD

**Issue by chassain** [nitpum/MMM-EmbedYoutube#14] opened 2019-08-29 13:33 UTC
Hello,

to begin, sorry for English.

I m using very often your module and it's great.
 Actually i have a magic Mirror with different modules, weather, iFrameReload, default, crypto,.... and the module MMM-page to scroll many of modules..
 My question is about the different pages. I would like to display your module in page 1 with one url and in page 2 but with another url...i can only display a playlist...

My other question is about problem when i use your module and MMM-iFrameReload (to have two different url to display on pages)...i can't display together video because i have an error saying : error renderer audio. start again your computer...Certainly because i can listen two video with one audio outside...

Thank you if you can help about one solution...have a good day

**Comment by nitpum** [comment] 2019-08-29 17:12
Can I see your MMM config and some screenshot of the problem?
I don't how the problem come yet. but If I know how you config and how the problems look like maybe I can help you.

**Comment by chassain** [comment] 2019-08-29 18:01
modules: [
		{
			module: "helloworld",
			position: "top_bar",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				text: "Bienvenue au Salon Sybille Vandyck"
		}
		},
		{
			module: "clock",
			disabled: false,
			position: "left",
			config: {
				displaySeconds: false,
				displayType: "digital",
				showWeek: false,
				analogFace: "face-003",
				}
		},
		{
			module: "calendar_monthly",
			disabled: false,
			position: "right"
		},
		{
			module: "MMM-DarkSkyForecast",
			header: "Cassis",
			position: "center",
			classes: "default everyone",
			disabled: false,
			config: {
				apikey: "1d9757c2f286db70573bb51cfce72bb3",
				latitude: "43.216068",
				longitude: "5.538550",      
				iconset: "4c",
				concise: false,
				forecastLayout: "table"
			}
		},  
		{
			module: "newsfeed",
			disabled: false,
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "BFM",
						url: "http://www.bfmtv.com/rss/info/flux-rss/flux-toutes-les-actualites/"
					},
					{
						titre: "Le Monde",
						url: "http://www.lemonde.fr/rss/une.xml"
					},
					{
						title: "20minutes",
						url: "http://www.20minutes.fr/rss/actu-france.xml"
					},
					{
						title: "lequipe",
						url: "http://www.lequipe.fr/rss/actu_rss.xml"
					}
				],
				showSourceTitle: false,
				showPublishDate: true
			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: false,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/9jHwwJgSTR4?rel=0&amp;autoplay=1&mute=0&loop=1"],	//aquarium
				width: "1000px", // Optional. Default: 100%
				height: "500px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-ImagesPhotos",
			position: "middle_center",
			config: {
				opacity: 0.9,
				animationSpeed: 500,
				updateInterval: 5000,
				maxWidth: "200%",
				maxHeight: "200%",
				}
		},
		{
			module:  "MMM-EmbedYoutube", // Chemin d' accï¿½s au module youtube de modules dossier exmaple: MagicMirror / modules / custom / MMM-EmbedYoutube / il est donc coutume / MMM-EmbedYoutube 
			position:  "middle_center",	 // Cela peut ï¿½tre l' un des les rï¿½gions. 
			config: {
			 // Voir 'Options de configuration' dans README.md pour plus d'informations. 
				video_id: "dxekoD1b3_o",	// info
				loop: false,
				autoplay: true,
				showinfo: false,
				width: 1000, // Optional. Default: 100% 		
				height: 450, //Optional. Default: 100px
				}
		},
		{
        		module: "MMM-pages",
			disabled: false,
        		config: {
                		modules:
				[[ "MMM-ImagesPhotos" , "newsfeed" , "helloworld" ],
				[ "MMM-iFrameReload" , "helloworld" , "newsfeed" ],
				[ 'clock' , "MMM-DarkSkyForecast" ,"calendar_monthly" , "helloworld" ],
				[ "MMM-EmbedYoutube" ]],
        			rotationTime: 30000,
				}
    		},

**Comment by chassain** [comment] 2019-08-29 18:07
![20190829_200546](https://user-images.githubusercontent.com/32990929/63965010-99760880-ca98-11e9-8295-417059626b97.jpg)

**Comment by chassain** [comment] 2019-08-29 18:08
there is no autoplay and we can se : error renderer audio. start again your computer

Thanks

**Comment by chassain** [comment] 2019-08-29 18:14
the other video is ok on page 2 with iframereload but the problem is not your module (of course)..cause i have the same problem when i use two videos on the same page (and module iframe) : tested now !

**Comment by chassain** [comment] 2019-08-29 18:42
when i use playlist with the two URL in your module it's ok..it's a solution. when the first is finish the second start ..but i will be nice to see a alternate between both (cause i can put a url with live information)..the solution will be may be to start 5 min with a video, 5 min with the other in the same iframe and page....
and of course it 's my first mm and i noob with javascript...very noob :)

**Comment by chassain** [comment] 2019-08-30 19:30
hello,

some news about pm2 logs

Failed to create permanent mapping for memfd region with ID = 207878710
0|mm | Failed to regester memfd mempool. Reason: could not attach memfd SHM ID to pipe
0|mm | mmap() failed: Cannot allocate memory
0|mm | Failed to create permanent mapping for memfd region with ID = 1648210477
0|mm | mmap() failed: Cannot allocate memory
0|mm | Failed to create permanent mapping for memfd region with ID = 1088771516
0|mm | Ignoring received block reference with non-registered memfd ID = 1088771516
0|mm | mmap() failed: Cannot allocate memory
0|mm | Failed to create permanent mapping for memfd region with ID = 3067665855
0|mm | Failed to regester memfd mempool. Reason: could not attach memfd SHM ID to pipe
0|mm | mmap() failed: Cannot allocate memory
0|mm | Failed to create permanent mapping for memfd region with ID = 1648210477
0|mm | mmap() failed: Cannot allocate memory
0|mm | Failed to create permanent mapping for memfd region with ID = 3337011850
0|mm | Ignoring received block reference with non-registered memfd ID = 3337011850

**Comment by nitpum** [comment] 2019-09-01 14:25
Sorry for not respond in few days. 
I can't find a permanent solution yet, but I found a temporary solution to play video in two page.
Just duplicate MMM-EmbedYoutbue and rename it

First you need to duplicate `MMM-EmbedYoutube` modules folder and rename the duplicated folder
to `MMM-EmbedYoutube2` 
now in modules folder you will have 2 of `MMM-EmbedYoutube`
- `modules/MMM-EmbedYoutube`
- `modules/MMM-EmbedYoutube2`

then rename `MMM-EmbedYoutube.js` in `modules/MMM-EmbedYoutube2/` to `MMM-EmbedYoutube2.js` and open it and change this line
```js
Module.register("MMM-EmbedYoutube", {
```
to
```js
Module.register("MMM-EmbedYoutube2", {
```


then in MMM `config.js` duplicate MMM-EmbedYoutube config and rename it like this
```js
{
		module:  "MMM-EmbedYoutube", 
                ...
},
{
		module:  "MMM-EmbedYoutube2",
                ...
}
```
and don't forget to change video_id in MMM-EmbedYoutube2 config
now you will have two of MMM-EmbedYoutube module one is for first page and other one
for second page.

in `MMM-pages` config will be like this
```js
{
    		module: "MMM-pages",
		disabled: false,
    		config: {
            		modules:
			[[ "MMM-ImagesPhotos" , "newsfeed" , "helloworld" ],
			[ "MMM-EmbedYoutube",  "helloworld" , "newsfeed" ],
			[ 'clock' , "MMM-DarkSkyForecast" ,"calendar_monthly" , "helloworld" ],
			[ "MMM-EmbedYoutube2" ]],
    			rotationTime: 30000,
			}
},
```

**Comment by chassain** [comment] 2019-09-01 14:53
hello ,

thanks for your answer. i have test this before but no way..mmap() failed: Cannot allocate memory is the pb about video's display and not your beautifull module. i'm looking for solutions but anyway. i m afraid to reset my sd card and restart configurations to be ok....thanks again

**Comment by chassain** [comment] 2019-09-02 07:49
hello,

Just for information. It's now ok after reset SD card...thanks a lot again for help and your work..See you !

**Comment by nitpum** [comment] 2019-09-02 07:57
I'm happy that you can fix the problem now, if you have any problem or suggestion for module you tell me here again.

The problem is solved  so I'm will close this issue

Have a nice day 😄

**Closed by nitpum** 2019-09-02 07:57 UTC

**Comment by chassain** [comment] 2019-09-02 08:49
I have always some suggestions :) ....like;;i would like to display "embed video" all time (page 1) "embed1 video" only in october to march (page3) and "embed2 video" to the rest of the year (same page)...
Embed video is for live info
embed1 video is for fireplace
embed2 video is for aquarium live

You see the idea...:)
